# Generated by Django 3.0.1 on 2020-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0004_auto_20200504_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esp41',
            old_name='pm03',
            new_name='p03',
        ),
        migrations.RenameField(
            model_name='esp41',
            old_name='pm05',
            new_name='p05',
        ),
        migrations.RenameField(
            model_name='esp41',
            old_name='pm50',
            new_name='p10',
        ),
        migrations.RemoveField(
            model_name='esp11',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp12',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp21',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp22',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp31',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp32',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp41',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='esp42',
            name='topic',
        ),
        migrations.AddField(
            model_name='esp41',
            name='p25',
            field=models.IntegerField(default=0),
        ),
    ]
