# Generated by Django 3.0.1 on 2020-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0005_auto_20200517_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('soilmoisture1', models.FloatField(default=0)),
                ('soilmoisture2', models.FloatField(default=0)),
                ('soilmoisture3', models.FloatField(default=0)),
                ('soilmoisture4', models.FloatField(default=0)),
                ('soilmoisture5', models.FloatField(default=0)),
                ('soilmoisture6', models.FloatField(default=0)),
                ('soilmoisture7', models.FloatField(default=0)),
                ('soilmoisture8', models.FloatField(default=0)),
                ('p03', models.FloatField(default=0)),
                ('p05', models.FloatField(default=0)),
                ('p10', models.FloatField(default=0)),
                ('p25', models.FloatField(default=0)),
                ('pm10', models.FloatField(default=0)),
                ('pm25', models.FloatField(default=0)),
                ('pm100', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('temperatureEsp', models.FloatField(default=0)),
                ('soiltempC', models.FloatField(default=0)),
                ('soiltempF', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='esp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp', models.CharField(max_length=10)),
                ('status', models.BinaryField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='esp11',
        ),
        migrations.DeleteModel(
            name='esp12',
        ),
        migrations.DeleteModel(
            name='esp21',
        ),
        migrations.DeleteModel(
            name='esp22',
        ),
        migrations.DeleteModel(
            name='esp31',
        ),
        migrations.DeleteModel(
            name='esp32',
        ),
        migrations.DeleteModel(
            name='esp41',
        ),
        migrations.DeleteModel(
            name='esp42',
        ),
    ]
