# Generated by Django 3.0.5 on 2020-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='moisturevalue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm03',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm05',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm100',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm25',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='pm50',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='soiltempC',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='soiltempF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='topic',
            field=models.CharField(default='Null', max_length=40),
        ),
    ]
