# Generated by Django 3.0.5 on 2020-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0002_auto_20200504_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='esp11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp31',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='esp42',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('moisturevalue', models.FloatField(default=0)),
                ('topic', models.CharField(default='Null', max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='sensor',
            new_name='esp41',
        ),
    ]
