# Generated by Django 3.0.1 on 2020-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0006_auto_20200517_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
